export const authStatus={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED"
}

export const regStatus={
REG_REQUEST:"REG_REQUEST",
REG_SUCCESS:"REG_SUCCESS",
REG_FAILED:"REG_FAILED"
}

export const otpStatus={
OTP_REQUEST :"OTP_REQUEST",
OTP_UPDATE:"OTP_UPDATE",
OTP_SUCCESS :"OTP_SUCCESS",
OTP_FAILED :"OTP_FAILED"
}
// export const generalStatus={
// GENERAL_REQUEST :"GENERAL_REQUEST",
// GENERAL_SUCCESS :"GENERAL_SUCCESS",
// GENERAL_FAILED :"GENERAL_FAILED"
// }



export const logoutStatus={
LOGOUT_REQUEST:"LOGOUT_REQUEST",
LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
LOGOUT_FAILED:"LOGOUT_FAILED"
}